### ISSUE TITLE
Add vKSM support

### ISSUE THREAD

**Issue by nud3l** [interlay/bridge#109] opened 2023-07-14 07:00 UTC
Add support to transfer vKSM from Bifrost

**Comment by bvotteler** [comment] 2023-07-18 04:48
This seems to be a duplicate of #42 , which was resolved in this PR: #46 .
I'll check with @tomjeatt if the option appears on the UI, or if something might be missing.

**Comment by bvotteler** [comment] 2023-07-18 09:47
Confirmed this already works since completing #42 . Closing as duplicate.

**Closed by bvotteler** 2023-07-18 09:47 UTC
Labels: enhancement, prio:high
